const API="/api",$=s=>document.querySelector(s),today=()=>new Date().toISOString().slice(0,10);
const STATUS_LABELS={AVAILABLE:"사용 가능",IN_USE:"사용 중",RESERVED:"예약",FAULTY:"장애",RMA:"RMA",REPAIR:"수리 중",DISPOSED:"폐기",LOST:"분실",UNKNOWN:"확인 필요"};
const esc=v=>String(v??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#39;"}[c]));
let inventory={totals:{},items:[]},quoteParts=[],toastTimer;
async function api(path,opt={}){const r=await fetch(API+path,{...opt,headers:{"Content-Type":"application/json",...(opt.headers||{})}}),d=await r.json().catch(()=>({}));if(!r.ok)throw new Error(d.detail||`요청 실패 (${r.status})`);return d}
function toast(message){clearTimeout(toastTimer);$("#toast").textContent=message;$("#toast").hidden=false;toastTimer=setTimeout(()=>{$("#toast").hidden=true},4000)}
function sum(items,key){return items.reduce((n,x)=>n+Number(x[key]||0),0)}
function filtered(){const site=$("#stock-site").value,type=$("#stock-type").value;return inventory.items.filter(x=>(!site||x.site_type===site)&&(!type||x.asset_type===type))}
function populateTypes(){const select=$("#stock-type"),selected=select.value,types=[...new Set(inventory.items.map(x=>x.asset_type))].sort();select.innerHTML='<option value="">전체 유형</option>'+types.map(x=>`<option value="${esc(x)}">${esc(x)}</option>`).join("");if(types.includes(selected))select.value=selected}
function renderInventory(){const items=filtered(),metrics=[["등록 자산",sum(items,"registered"),""],["정상 재고",sum(items,"normal"),""],["사용 가능",sum(items,"available"),""],["장애 자산",sum(items,"faulty"),"fault"]];$("#stock-cards").innerHTML=metrics.map(([l,v,k])=>`<article class="metric ${k}"><span class="label">${l}</span><strong class="value">${v.toLocaleString("ko-KR")}</strong></article>`).join("");const faulty=sum(items,"faulty");$("#fault-notice").hidden=!faulty;$("#fault-title").textContent=`장애 자산 ${faulty.toLocaleString("ko-KR")}개가 별도로 분리되어 있습니다.`;$("#row-count").textContent=`${items.length}개 그룹`;const body=$("#stock-body");$("#stock-empty").hidden=!!items.length;body.closest(".table-wrap").hidden=!items.length;body.innerHTML=items.map(x=>`<tr><td data-label="자산 유형"><strong>${esc(x.asset_type)}</strong></td><td data-label="사양">${esc(x.specification_label||"—")}</td><td data-label="Site">${esc(x.site_type)}</td><td data-label="정상 재고" class="number">${x.normal}</td><td data-label="사용 가능" class="number">${x.available}</td><td data-label="사용 중" class="number">${x.in_use}</td><td data-label="장애" class="number ${x.faulty?"fault-number":""}">${x.faulty}</td><td data-label="폐기" class="number">${x.disposed}</td><td><button class="button secondary small" type="button" data-view-assets data-type="${esc(x.asset_type)}" data-site="${esc(x.site_type)}" data-group="${esc(x.group_key||"")}" data-specification="${esc(x.specification_label||"")}">자산 보기</button></td></tr>`).join("")}
async function loadInventory(){const b=$("#refresh-stock");b.disabled=true;try{inventory=await api("/inventory/summary?group_by=specification");populateTypes();renderInventory();$("#updated-at").textContent=`${new Date().toLocaleString("ko-KR")} 갱신`}catch(e){toast(`재고 현황을 불러오지 못했습니다: ${e.message}`)}finally{b.disabled=false}}
async function openAssets(type,site,groupKey="",specification=""){const dialog=$("#asset-dialog");$("#asset-dialog-title").textContent=[type,site,specification].filter(Boolean).join(" · ");$("#asset-list").innerHTML='<p class="empty-state">자산 목록을 불러오는 중입니다.</p>';dialog.showModal();try{const list=await api(`/assets?${new URLSearchParams({asset_type:type,site_type:site,...(groupKey?{group_key:groupKey}:{})})}`);$("#asset-list").innerHTML=list.length?list.map(x=>`<a class="asset-row" href="/a/${encodeURIComponent(x.asset_code)}"><span><strong>${esc(x.asset_code)}</strong><small>${esc(x.asset_type)} · ${esc(x.site_type)}</small></span><span class="status ${x.status.toLowerCase()}">${esc(STATUS_LABELS[x.status]||x.status)}</span></a>`).join(""):'<div class="empty-state"><h3>해당 자산이 없습니다</h3></div>'}catch(e){$("#asset-list").innerHTML=`<div class="empty-state"><h3>목록을 불러오지 못했습니다</h3><p>${esc(e.message)}</p></div>`}}
function asOf(prices,date){return prices.filter(x=>x.date<=date).sort((a,b)=>b.date.localeCompare(a.date))[0]||null}
function renderQuotes(){const q=$("#quote-search").value.trim().toLowerCase(),date=$("#quote-date").value||today(),rows=quoteParts.filter(x=>!q||x.name.toLowerCase().includes(q)||x.category.toLowerCase().includes(q)),body=$("#quote-body");$("#quote-empty").hidden=!!rows.length;body.closest(".table-wrap").hidden=!rows.length;body.innerHTML=rows.map(x=>{const p=asOf(x.prices,date);return`<tr><td data-label="부품명"><input aria-label="${esc(x.name)} 부품명" value="${esc(x.name)}" data-quote-name="${esc(x.id)}"></td><td data-label="카테고리">${esc(x.category)}</td><td data-label="단가" class="number"><input aria-label="${esc(x.name)} 단가" inputmode="numeric" value="${p?p.price.toLocaleString("ko-KR"):""}" data-quote-price="${esc(x.id)}"></td><td><button class="button danger small" type="button" data-delete-quote="${esc(x.id)}">삭제</button></td></tr>`}).join("")}
async function loadQuotes(){try{quoteParts=await api("/quotes");renderQuotes()}catch(e){toast(`견적을 불러오지 못했습니다: ${e.message}`)}}
function selectTab(name){document.querySelectorAll("[role=tab]").forEach(tab=>{const on=tab.dataset.tab===name;tab.classList.toggle("active",on);tab.setAttribute("aria-selected",String(on));$("#panel-"+tab.dataset.tab).hidden=!on});if(name==="quote"&&!quoteParts.length)loadQuotes()}
function renderLabelSheets(codes,startPosition){const pages=[];let codeIndex=0,pageIndex=0;while(codeIndex<codes.length){const blankCount=pageIndex===0?startPosition-1:0,slots=Array(104).fill(null);for(let slot=blankCount;slot<104&&codeIndex<codes.length;slot+=1)slots[slot]=codes[codeIndex++];pages.push(slots);pageIndex+=1}$("#label-preview").innerHTML=pages.map((slots,page)=>`<section class="label-sheet" aria-label="QR 라벨 ${page+1}쪽">${slots.map(code=>code?`<div class="qr-label"><img src="/api/asset-labels/${encodeURIComponent(code)}/qr.svg" alt="${esc(code)} QR"><span>${esc(code)}</span></div>`:'<div class="qr-label blank" aria-hidden="true"></div>').join("")}</section>`).join("")}
async function waitForLabelImages(){const images=[...document.querySelectorAll("#label-preview img")];await Promise.all(images.map(image=>image.complete?Promise.resolve():new Promise(resolve=>{image.addEventListener("load",resolve,{once:true});image.addEventListener("error",resolve,{once:true})})));return images.every(image=>image.naturalWidth>0)}
document.querySelectorAll("[role=tab]").forEach(tab=>{tab.addEventListener("click",()=>selectTab(tab.dataset.tab));tab.addEventListener("keydown",e=>{const tabs=[...document.querySelectorAll("[role=tab]")],i=tabs.indexOf(tab);let next=null;if(e.key==="ArrowRight")next=tabs[(i+1)%tabs.length];if(e.key==="ArrowLeft")next=tabs[(i-1+tabs.length)%tabs.length];if(e.key==="Home")next=tabs[0];if(e.key==="End")next=tabs[tabs.length-1];if(next){e.preventDefault();next.focus();selectTab(next.dataset.tab)}})});$("#stock-site").addEventListener("change",renderInventory);$("#stock-type").addEventListener("change",renderInventory);$("#refresh-stock").addEventListener("click",loadInventory);$("#stock-body").addEventListener("click",e=>{const b=e.target.closest("[data-view-assets]");if(b)openAssets(b.dataset.type,b.dataset.site,b.dataset.group,b.dataset.specification)});$("[data-dialog-close]").addEventListener("click",()=>$("#asset-dialog").close());$("#asset-dialog").addEventListener("click",e=>{if(e.target===e.currentTarget)e.currentTarget.close()});$("#quote-search").addEventListener("input",renderQuotes);$("#quote-date").addEventListener("change",renderQuotes);
$("#quote-add-form").addEventListener("submit",async e=>{e.preventDefault();const name=$("#quote-new-name").value.trim(),price=Number($("#quote-new-price").value.replace(/[^0-9]/g,"")||0);try{const made=await api("/quotes",{method:"POST",body:JSON.stringify({name})});if(price)await api(`/quotes/${made.id}/prices`,{method:"PUT",body:JSON.stringify({date:$("#quote-date").value||today(),price})});e.currentTarget.reset();$("#quote-date").value=today();await loadQuotes();toast("견적 항목을 추가했습니다.")}catch(err){toast(`추가하지 못했습니다: ${err.message}`)}});
$("#quote-body").addEventListener("change",async e=>{const nameId=e.target.dataset.quoteName,priceId=e.target.dataset.quotePrice;try{if(nameId)await api(`/quotes/${nameId}`,{method:"PATCH",body:JSON.stringify({name:e.target.value.trim()})});if(priceId)await api(`/quotes/${priceId}/prices`,{method:"PUT",body:JSON.stringify({date:$("#quote-date").value||today(),price:Number(e.target.value.replace(/[^0-9]/g,"")||0)})});await loadQuotes();toast("견적을 저장했습니다.")}catch(err){toast(`저장하지 못했습니다: ${err.message}`)}});
$("#quote-body").addEventListener("click",async e=>{const id=e.target.dataset.deleteQuote;if(!id||!confirm("이 견적 항목과 단가 기록을 삭제할까요?"))return;try{await api(`/quotes/${id}`,{method:"DELETE"});await loadQuotes();toast("견적 항목을 삭제했습니다.")}catch(err){toast(`삭제하지 못했습니다: ${err.message}`)}});
$("#label-issue-form").addEventListener("submit",async e=>{e.preventDefault();const quantity=Number($("#label-quantity").value),startPosition=Number($("#label-start-position").value),kind=$("#label-kind").value,labelName=kind==="server"?"서버 ID":kind==="network"?"네트워크 장비 ID":"Asset ID",endpoint=kind==="server"?"/server-labels":kind==="network"?"/network-labels":"/asset-labels",button=$("#issue-labels"),actions=$("#label-result-actions");if(!Number.isInteger(quantity)||quantity<1||quantity>500||!Number.isInteger(startPosition)||startPosition<1||startPosition>104)return;button.disabled=true;button.textContent=`${labelName} 발급 중…`;actions.hidden=true;try{const issued=await api(endpoint,{method:"POST",body:JSON.stringify({quantity})});renderLabelSheets(issued.asset_codes,startPosition);actions.hidden=false;$("#print-labels").disabled=true;$("#label-status").textContent=`${issued.asset_codes.length}개 ${labelName}를 발급하고 QR 이미지를 준비하는 중입니다.`;const ready=await waitForLabelImages();$("#print-labels").disabled=!ready;$("#label-status").textContent=ready?`${issued.asset_codes.length}개 ${labelName} 라벨이 준비됐습니다.`:"일부 QR 이미지를 불러오지 못했습니다. 새로고침 후 다시 시도하세요."}catch(err){toast(`라벨을 발급하지 못했습니다: ${err.message}`)}finally{button.disabled=false;button.textContent="ID 발급 및 라벨 생성"}});
$("#print-labels").addEventListener("click",()=>window.print());
$("#quote-date").value=today();loadInventory();
